In [1]:
import pandas as pd
import datetime
import sidetable

In [2]:
# Creo dataframe activity
activity = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv')

print(activity)

             Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0    1503960366    4/12/2016       13162       8.500000         8.500000
1    1503960366    4/13/2016       10735       6.970000         6.970000
2    1503960366    4/14/2016       10460       6.740000         6.740000
3    1503960366    4/15/2016        9762       6.280000         6.280000
4    1503960366    4/16/2016       12669       8.160000         8.160000
..          ...          ...         ...            ...              ...
935  8877689391     5/8/2016       10686       8.110000         8.110000
936  8877689391     5/9/2016       20226      18.250000        18.250000
937  8877689391    5/10/2016       10733       8.150000         8.150000
938  8877689391    5/11/2016       21420      19.559999        19.559999
939  8877689391    5/12/2016        8064       6.120000         6.120000

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                         0.0                1.88                      0.55
1                         0.0                1.57                      0.69
2                         0.0                2.44                      0.40
3                         0.0                2.14                      1.26
4                         0.0                2.71                      0.41
..                        ...                 ...                       ...
935                       0.0                1.08                      0.20
936                       0.0               11.10                      0.80
937                       0.0                1.35                      0.46
938                       0.0               13.22                      0.41
939                       0.0                1.82                      0.04

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                   6.06                     0.00                 25
1                   4.71                     0.00                 21
2                   3.91                     0.00                 30
3                   2.83                     0.00                 29
4                   5.04                     0.00                 36
..                   ...                      ...                ...
935                 6.80                     0.00                 17
936                 6.24                     0.05                 73
937                 6.28                     0.00                 18
938                 5.89                     0.00                 88
939                 4.25                     0.00                 23

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                     13                   328               728      1985
1                     19                   217               776      1797
2                     11                   181              1218      1776
3                     34                   209               726      1745
4                     10                   221               773      1863
..                   ...                   ...               ...       ...
935                    4                   245              1174      2847
936                   19                   217              1131      3710
937                   11                   224              1187      2832
938                   12                   213              1127      3832
939                    1                   137               770      1849

[940 rows x 15 columns]

In [3]:
activity.isnull().sum()
# No hay valores vacios

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [5]:
# Creo dataframe calories
calories = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv')
print(calories)

               Id           ActivityHour  Calories
0      1503960366  4/12/2016 12:00:00 AM        81
1      1503960366   4/12/2016 1:00:00 AM        61
2      1503960366   4/12/2016 2:00:00 AM        59
3      1503960366   4/12/2016 3:00:00 AM        47
4      1503960366   4/12/2016 4:00:00 AM        48
...           ...                    ...       ...
22094  8877689391  5/12/2016 10:00:00 AM       126
22095  8877689391  5/12/2016 11:00:00 AM       192
22096  8877689391  5/12/2016 12:00:00 PM       321
22097  8877689391   5/12/2016 1:00:00 PM       101
22098  8877689391   5/12/2016 2:00:00 PM       113

[22099 rows x 3 columns]

In [6]:
calories.isnull().sum()
# No hay valores vacios

Id              0
ActivityHour    0
Calories        0
dtype: int64

In [7]:
# Cambio el formato de la columna ActivityHour
calories["ActivityHour"] = pd.to_datetime(calories["ActivityHour"])

/tmp/ipykernel_2859/615830490.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  calories["ActivityHour"] = pd.to_datetime(calories["ActivityHour"])

In [8]:
# Creo la columna ActivityHourFormatted con los datos de la columna ActivityHour
calories["ActivityHourFormatted"] = calories["ActivityHour"].dt.strftime("%d/%m/%Y %H:%M:%S")
print(calories)

               Id        ActivityHour  Calories ActivityHourFormatted
0      1503960366 2016-04-12 00:00:00        81   12/04/2016 00:00:00
1      1503960366 2016-04-12 01:00:00        61   12/04/2016 01:00:00
2      1503960366 2016-04-12 02:00:00        59   12/04/2016 02:00:00
3      1503960366 2016-04-12 03:00:00        47   12/04/2016 03:00:00
4      1503960366 2016-04-12 04:00:00        48   12/04/2016 04:00:00
...           ...                 ...       ...                   ...
22094  8877689391 2016-05-12 10:00:00       126   12/05/2016 10:00:00
22095  8877689391 2016-05-12 11:00:00       192   12/05/2016 11:00:00
22096  8877689391 2016-05-12 12:00:00       321   12/05/2016 12:00:00
22097  8877689391 2016-05-12 13:00:00       101   12/05/2016 13:00:00
22098  8877689391 2016-05-12 14:00:00       113   12/05/2016 14:00:00

[22099 rows x 4 columns]

In [9]:
# Elimino la columna ActivityHour
calories.drop(['ActivityHour'], axis=1, inplace=True)

In [10]:
# Creo un nuevo dataframe para separar los datos de fecha y horario
formatted=calories["ActivityHourFormatted"].str.split(expand=True)
formatted.columns=['ActivityDate', 'ActivityHour']
calories=pd.concat([calories,formatted], axis=1)

In [11]:
# Elimino la columna ActivityHourFormatted ya que se reemplazará por las nuevas columnas
calories.drop(['ActivityHourFormatted'], axis=1, inplace=True)

In [12]:
print(calories)

               Id  Calories ActivityDate ActivityHour
0      1503960366        81   12/04/2016     00:00:00
1      1503960366        61   12/04/2016     01:00:00
2      1503960366        59   12/04/2016     02:00:00
3      1503960366        47   12/04/2016     03:00:00
4      1503960366        48   12/04/2016     04:00:00
...           ...       ...          ...          ...
22094  8877689391       126   12/05/2016     10:00:00
22095  8877689391       192   12/05/2016     11:00:00
22096  8877689391       321   12/05/2016     12:00:00
22097  8877689391       101   12/05/2016     13:00:00
22098  8877689391       113   12/05/2016     14:00:00

[22099 rows x 4 columns]

In [7]:
intensities = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv')
print(intensities)

               Id           ActivityHour  TotalIntensity  AverageIntensity
0      1503960366  4/12/2016 12:00:00 AM              20          0.333333
1      1503960366   4/12/2016 1:00:00 AM               8          0.133333
2      1503960366   4/12/2016 2:00:00 AM               7          0.116667
3      1503960366   4/12/2016 3:00:00 AM               0          0.000000
4      1503960366   4/12/2016 4:00:00 AM               0          0.000000
...           ...                    ...             ...               ...
22094  8877689391  5/12/2016 10:00:00 AM              12          0.200000
22095  8877689391  5/12/2016 11:00:00 AM              29          0.483333
22096  8877689391  5/12/2016 12:00:00 PM              93          1.550000
22097  8877689391   5/12/2016 1:00:00 PM               6          0.100000
22098  8877689391   5/12/2016 2:00:00 PM               9          0.150000

[22099 rows x 4 columns]

In [8]:
intensities.isnull().sum()
# No hay valores vacios

Id                  0
ActivityHour        0
TotalIntensity      0
AverageIntensity    0
dtype: int64

In [15]:
# Repito los mismos pasos de calories para el dataframe intensities
intensities["ActivityHour"] = pd.to_datetime(intensities["ActivityHour"])

/tmp/ipykernel_2859/1791546720.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  intensities["ActivityHour"] = pd.to_datetime(intensities["ActivityHour"])

In [16]:
intensities["ActivityHourFormatted"] = intensities["ActivityHour"].dt.strftime("%d/%m/%Y %H:%M:%S")
print(intensities)

               Id        ActivityHour  TotalIntensity  AverageIntensity  \
0      1503960366 2016-04-12 00:00:00              20          0.333333
1      1503960366 2016-04-12 01:00:00               8          0.133333
2      1503960366 2016-04-12 02:00:00               7          0.116667
3      1503960366 2016-04-12 03:00:00               0          0.000000
4      1503960366 2016-04-12 04:00:00               0          0.000000
...           ...                 ...             ...               ...
22094  8877689391 2016-05-12 10:00:00              12          0.200000
22095  8877689391 2016-05-12 11:00:00              29          0.483333
22096  8877689391 2016-05-12 12:00:00              93          1.550000
22097  8877689391 2016-05-12 13:00:00               6          0.100000
22098  8877689391 2016-05-12 14:00:00               9          0.150000

      ActivityHourFormatted
0       12/04/2016 00:00:00
1       12/04/2016 01:00:00
2       12/04/2016 02:00:00
3       12/04/2016 03:00:00
4       12/04/2016 04:00:00
...                     ...
22094   12/05/2016 10:00:00
22095   12/05/2016 11:00:00
22096   12/05/2016 12:00:00
22097   12/05/2016 13:00:00
22098   12/05/2016 14:00:00

[22099 rows x 5 columns]

In [17]:
intensities.drop(['ActivityHour'], axis=1, inplace=True)

In [18]:
formatted2=intensities["ActivityHourFormatted"].str.split(expand=True)
formatted2.columns=['ActivityDate', 'ActivityHour']
intensities=pd.concat([intensities,formatted2], axis=1)

In [19]:
intensities.drop(['ActivityHourFormatted'], axis=1, inplace=True)

In [20]:
print(intensities)

               Id  TotalIntensity  AverageIntensity ActivityDate ActivityHour
0      1503960366              20          0.333333   12/04/2016     00:00:00
1      1503960366               8          0.133333   12/04/2016     01:00:00
2      1503960366               7          0.116667   12/04/2016     02:00:00
3      1503960366               0          0.000000   12/04/2016     03:00:00
4      1503960366               0          0.000000   12/04/2016     04:00:00
...           ...             ...               ...          ...          ...
22094  8877689391              12          0.200000   12/05/2016     10:00:00
22095  8877689391              29          0.483333   12/05/2016     11:00:00
22096  8877689391              93          1.550000   12/05/2016     12:00:00
22097  8877689391               6          0.100000   12/05/2016     13:00:00
22098  8877689391               9          0.150000   12/05/2016     14:00:00

[22099 rows x 5 columns]

In [21]:
heartrate = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv')
print(heartrate)

                 Id                  Time  Value
0        2022484408  4/12/2016 7:21:00 AM     97
1        2022484408  4/12/2016 7:21:05 AM    102
2        2022484408  4/12/2016 7:21:10 AM    105
3        2022484408  4/12/2016 7:21:20 AM    103
4        2022484408  4/12/2016 7:21:25 AM    101
...             ...                   ...    ...
2483653  8877689391  5/12/2016 2:43:53 PM     57
2483654  8877689391  5/12/2016 2:43:58 PM     56
2483655  8877689391  5/12/2016 2:44:03 PM     55
2483656  8877689391  5/12/2016 2:44:18 PM     55
2483657  8877689391  5/12/2016 2:44:28 PM     56

[2483658 rows x 3 columns]

In [9]:
sleep = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv')
print(sleep)

             Id               SleepDay  TotalSleepRecords  TotalMinutesAsleep  \
0    1503960366  4/12/2016 12:00:00 AM                  1                 327
1    1503960366  4/13/2016 12:00:00 AM                  2                 384
2    1503960366  4/15/2016 12:00:00 AM                  1                 412
3    1503960366  4/16/2016 12:00:00 AM                  2                 340
4    1503960366  4/17/2016 12:00:00 AM                  1                 700
..          ...                    ...                ...                 ...
408  8792009665  4/30/2016 12:00:00 AM                  1                 343
409  8792009665   5/1/2016 12:00:00 AM                  1                 503
410  8792009665   5/2/2016 12:00:00 AM                  1                 415
411  8792009665   5/3/2016 12:00:00 AM                  1                 516
412  8792009665   5/4/2016 12:00:00 AM                  1                 439

     TotalTimeInBed
0               346
1               407
2               442
3               367
4               712
..              ...
408             360
409             527
410             423
411             545
412             463

[413 rows x 5 columns]

In [10]:
sleep.isnull().sum()
# No hay valores vacios

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

In [24]:
sleep["SleepDay"] = pd.to_datetime(sleep["SleepDay"])

/tmp/ipykernel_2859/4089730069.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sleep["SleepDay"] = pd.to_datetime(sleep["SleepDay"])

In [25]:
sleep["SleepDayFormatted"] = sleep["SleepDay"].dt.strftime("%d/%m/%Y %H:%M:%S")
print(sleep)

             Id   SleepDay  TotalSleepRecords  TotalMinutesAsleep  \
0    1503960366 2016-04-12                  1                 327
1    1503960366 2016-04-13                  2                 384
2    1503960366 2016-04-15                  1                 412
3    1503960366 2016-04-16                  2                 340
4    1503960366 2016-04-17                  1                 700
..          ...        ...                ...                 ...
408  8792009665 2016-04-30                  1                 343
409  8792009665 2016-05-01                  1                 503
410  8792009665 2016-05-02                  1                 415
411  8792009665 2016-05-03                  1                 516
412  8792009665 2016-05-04                  1                 439

     TotalTimeInBed    SleepDayFormatted
0               346  12/04/2016 00:00:00
1               407  13/04/2016 00:00:00
2               442  15/04/2016 00:00:00
3               367  16/04/2016 00:00:00
4               712  17/04/2016 00:00:00
..              ...                  ...
408             360  30/04/2016 00:00:00
409             527  01/05/2016 00:00:00
410             423  02/05/2016 00:00:00
411             545  03/05/2016 00:00:00
412             463  04/05/2016 00:00:00

[413 rows x 6 columns]

In [26]:
sleep.drop(['SleepDay'], axis=1, inplace=True)

In [27]:
formatted3=sleep["SleepDayFormatted"].str.split(expand=True)
formatted3.columns=['SleepDate', 'SleepHour']
sleep=pd.concat([sleep,formatted3], axis=1)

In [28]:
sleep.drop(['SleepDayFormatted'], axis=1, inplace=True)

In [29]:
print(sleep)

             Id  TotalSleepRecords  TotalMinutesAsleep  TotalTimeInBed  \
0    1503960366                  1                 327             346
1    1503960366                  2                 384             407
2    1503960366                  1                 412             442
3    1503960366                  2                 340             367
4    1503960366                  1                 700             712
..          ...                ...                 ...             ...
408  8792009665                  1                 343             360
409  8792009665                  1                 503             527
410  8792009665                  1                 415             423
411  8792009665                  1                 516             545
412  8792009665                  1                 439             463

      SleepDate SleepHour
0    12/04/2016  00:00:00
1    13/04/2016  00:00:00
2    15/04/2016  00:00:00
3    16/04/2016  00:00:00
4    17/04/2016  00:00:00
..          ...       ...
408  30/04/2016  00:00:00
409  01/05/2016  00:00:00
410  02/05/2016  00:00:00
411  03/05/2016  00:00:00
412  04/05/2016  00:00:00

[413 rows x 6 columns]

In [30]:
weight = pd.read_csv('/home/Escritorio/ProyectoBellaBeat/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv')
print(weight)

            Id                   Date    WeightKg  WeightPounds   Fat  \
0   1503960366   5/2/2016 11:59:59 PM   52.599998    115.963147  22.0
1   1503960366   5/3/2016 11:59:59 PM   52.599998    115.963147   NaN
2   1927972279   4/13/2016 1:08:52 AM  133.500000    294.317120   NaN
3   2873212765  4/21/2016 11:59:59 PM   56.700001    125.002104   NaN
4   2873212765  5/12/2016 11:59:59 PM   57.299999    126.324875   NaN
..         ...                    ...         ...           ...   ...
62  8877689391    5/6/2016 6:43:35 AM   85.000000    187.392923   NaN
63  8877689391    5/8/2016 7:35:53 AM   85.400002    188.274775   NaN
64  8877689391    5/9/2016 6:39:44 AM   85.500000    188.495234   NaN
65  8877689391   5/11/2016 6:51:47 AM   85.400002    188.274775   NaN
66  8877689391   5/12/2016 6:42:53 AM   84.000000    185.188300   NaN

          BMI  IsManualReport          LogId
0   22.650000            True  1462233599000
1   22.650000            True  1462319999000
2   47.540001           False  1460509732000
3   21.450001            True  1461283199000
4   21.690001            True  1463097599000
..        ...             ...            ...
62  25.440001           False  1462517015000
63  25.559999           False  1462692953000
64  25.610001           False  1462775984000
65  25.559999           False  1462949507000
66  25.139999           False  1463035373000

[67 rows x 8 columns]

In [31]:
activity.stb.counts()
# Son 33 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
SedentaryActiveDistance,940,9,0.0,858,0.07,1
LoggedActivitiesDistance,940,19,0.0,908,4.081692,1
ActivityDate,940,31,4/12/2016,33,5/12/2016,21
Id,940,33,1503960366,31,4057192912,4
FairlyActiveMinutes,940,81,0,384,69,1
VeryActiveMinutes,940,122,0,409,88,1
ModeratelyActiveDistance,940,211,0.0,386,1.22,1
VeryActiveDistance,940,333,0.0,413,9.1,1
LightlyActiveMinutes,940,335,0,84,218,1
LightActiveDistance,940,491,0.0,85,2.34,1
SedentaryMinutes,940,549,1440,79,770,1
TrackerDistance,940,613,0.0,78,8.54,1
TotalDistance,940,615,0.0,78,1.46,1
Calories,940,734,1980,13,2053,1
TotalSteps,940,842,0,77,9799,1

In [32]:
calories.stb.counts()
# Son 33 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
ActivityHour,22099,24,00:00:00,934,23:00:00,903
ActivityDate,22099,31,12/04/2016,792,12/05/2016,259
Id,22099,33,1624580081,736,4057192912,88
Calories,22099,442,86,1068,524,1

In [33]:
intensities.stb.counts()
# Son 33 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
ActivityHour,22099,24,00:00:00,934,23:00:00,903
ActivityDate,22099,31,12/04/2016,792,12/05/2016,259
Id,22099,33,1624580081,736,4057192912,88
TotalIntensity,22099,175,0,9097,179,1
AverageIntensity,22099,175,0.0,9097,2.983333,1

In [34]:
heartrate.stb.counts()
# Son 14 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
Id,2483658,14,4020332650,285461,2026352035,2490
Value,2483658,168,64,69071,201,1
Time,2483658,961274,4/20/2016 11:52:15 AM,12,5/12/2016 2:44:28 PM,1

In [35]:
sleep.stb.counts()
# Son 24 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
SleepHour,413,1,00:00:00,413,00:00:00,413
TotalSleepRecords,413,3,1,367,3,3
Id,413,24,8378563200,32,2320127002,1
SleepDate,413,31,15/04/2016,17,12/05/2016,8
TotalTimeInBed,413,242,402,6,396,1
TotalMinutesAsleep,413,256,442,7,115,1

In [36]:
weight.stb.counts()
# Son 8 clientes

,count,unique,most_freq,most_freq_count,least_freq,least_freq_count
IsManualReport,67,2,True,41,False,26
Fat,2,2,22.0,1,22.0,1
Id,67,8,6962181067,30,1927972279,1
WeightKg,67,34,61.400002,5,133.5,1
WeightPounds,67,34,135.363832,5,294.31712,1
BMI,67,36,23.889999,5,47.540001,1
Date,67,56,5/2/2016 11:59:59 PM,3,4/13/2016 1:08:52 AM,1
LogId,67,56,1462233599000,3,1460509732000,1

In [37]:
# Para el análisis se utilizaran los dataframes activity, intensities, calories e incluso sleep. En cuanto
# los dataframes heartrate y weigth no se utilizarán ya que al tener 14 y 8 clientes no son relevantes para
# analizar al ser tan pocos. Guardo las tablas echas en formato csv.

intensities.to_csv('intensities.csv')
calories.to_csv('calories.csv')
sleep.to_csv('sleep.csv')